# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_DATA_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT setval('processing_processtype_id_seq', ("
            "SELECT MAX(id)+1 FROM processing_processtype), false)",

            "SELECT setval('processing_processtype_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('processing_reagent_id_seq', ("
            "SELECT MAX(id)+1 FROM processing_reagent), false)",

            "SELECT setval('processing_reagent_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('processing_flaw_id_seq', ("
            "SELECT MAX(id)+1 FROM processing_flaw), false)",

            "SELECT setval('processing_flaw_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('processing_processing_id_seq', ("
            "SELECT MAX(id)+1 FROM processing_processing), false)",

            "SELECT setval('processing_processing_id_seq', 1, false)"
        ),
    ]
