# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='adminentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.AdminSection'),
        ),
    ]
