# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_initial_admin_enties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminentry',
            options={'verbose_name_plural': 'admin entries'},
        ),
    ]
