# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_DATA_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT setval('projects_project_id_seq', ("
            "SELECT MAX(id)+1 FROM projects_project), false)",

            "SELECT setval('projects_project_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('projects_grant_id_seq', ("
            "SELECT MAX(id)+1 FROM projects_grant), false)",

            "SELECT setval('projects_grant_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('projects_grantreport_id_seq', ("
            "SELECT MAX(id)+1 FROM projects_grantreport), false)",

            "SELECT setval('projects_grantreport_id_seq', 1, false)"
        ),
    ]
