# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_DATA_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT setval('misc_measurementunit_id_seq', ("
            "SELECT MAX(id)+1 FROM misc_measurementunit), false)",

            "SELECT setval('misc_measurementunit_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('misc_measurementtype_id_seq', ("
            "SELECT MAX(id)+1 FROM misc_measurementtype), false)",

            "SELECT setval('misc_measurementtype_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('misc_material_id_seq', ("
            "SELECT MAX(id)+1 FROM misc_material), false)",

            "SELECT setval('misc_material_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('misc_color_id_seq', ("
            "SELECT MAX(id)+1 FROM misc_color), false)",

            "SELECT setval('misc_color_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('misc_container_id_seq', ("
            "SELECT MAX(id)+1 FROM misc_container), false)",

            "SELECT setval('misc_container_id_seq', 1, false)"
        ),
    ]
