# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_ccdb', '0004_DATA_reset_sequences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='flaw',
            new_name='collection_flaw',
        ),
    ]
