# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-22 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_DATA_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT setval('species_species_id_seq', ("
            "SELECT MAX(id)+1 FROM species_species), false)",

            "SELECT setval('species_species_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('species_trapspecies_id_seq', ("
            "SELECT MAX(id)+1 FROM species_trapspecies), false)",

            "SELECT setval('species_trapspecies_id_seq', 1, false)"
        ),

        migrations.RunSQL(
            "SELECT setval('species_collectionspecies_id_seq', ("
            "SELECT MAX(id)+1 FROM species_collectionspecies), false)",

            "SELECT setval('species_collectionspecies_id_seq', 1, false)"
        ),
    ]
